### ISSUE TITLE
OneFileReader: Нужно написать тест на проверку частого обращения к файлу

### ISSUE THREAD

**Issue by ghost** [Harosich1/greetgo-conf2#2]
То есть, если к файлу обращаются тысячу раз в секунду, то они все берут кэш, а не происходит реальный запрос файла.

**Comment by Harosich1** [comment]
Вроде данный тест есть, или нужен какой то другой?

**Comment by Harosich1** [comment]
Вроде данный тест есть, или нужен какой то другой?

**Comment by Harosich1** [comment]
content__callTwice__butReadFsContentOnce()/// content__вызываемДважды__иОбращениеКФайловойСистемеДалаетсяТожеДваждыПотомуЧтоПрошёл_delayBetweenReadMs()/// **Тесты для проверки частого обращения к файлу**
